name: Rust CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust: [stable, beta, nightly]
    steps:
    - uses: actions/checkout@v4
    - run: rustup default ${{ matrix.rust }}
    - name: build
      run: cargo build --verbose
    - name: test
      run: cargo test --features std --tests --benches
  no_std:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: rustup default stable
    - run: rustup target add thumbv7m-none-eabi
    - name: no_std build
      run: cargo build --target thumbv7m-none-eabi --no-default-features
    - name: check default features
      run: cargo check
  rustfmt:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: rustup default stable && rustup component add rustfmt
    - name: Run rustfmt check
      run: cargo fmt -- --check
